#!/usr/bin/env python3
"""Cut the monogram's two letters out of Fraunces.

    python3 scripts/build-mark-paths.py        (or: npm run mark)

The mark is an interlocking S and C. It is drawn in the site's own display
face rather than traced from the prototype sheet: there is no vector source
for that drawing, a trace from a screenshot would be a worse object than a
construction, and using Fraunces makes the lockup — the mark beside SENSO
COMUNE, which is already set in Fraunces — one typeface instead of two.

The instance is the display end of the optical-size axis at the subset's full
weight, which is where Fraunces draws its heaviest stems against its finest
hairlines: the high-contrast, seriffed letter the prototype is built from.

Output is scripts/mark-paths.js, committed, so building the site needs Node
and nothing else. Re-run this only when the font or the instance changes.
"""
import json, sys
from pathlib import Path
from fontTools.ttLib import TTFont
from fontTools.varLib import instancer
from fontTools.pens.svgPathPen import SVGPathPen
from fontTools.pens.boundsPen import BoundsPen

ROOT = Path(__file__).resolve().parent.parent
FONT = ROOT / "public/fonts/fraunces-latin.woff2"
OPSZ, WGHT = 40, 700          # display drawing, full weight of the subset

f = TTFont(FONT)
f = instancer.instantiateVariableFont(f, {"opsz": OPSZ, "wght": WGHT})
upem = f["head"].unitsPerEm
gs = f.getGlyphSet()
cmap = f.getBestCmap()

out = {"upem": upem, "opsz": OPSZ, "wght": WGHT, "glyphs": {}}
for ch in "SC":
    name = cmap[ord(ch)]
    pen = SVGPathPen(gs, ntos=lambda v: str(round(v, 1)))
    gs[name].draw(pen)
    bp = BoundsPen(gs)
    gs[name].draw(bp)
    x0, y0, x1, y1 = bp.bounds
    out["glyphs"][ch] = {"d": pen.getCommands(),
                         "bbox": [round(v, 1) for v in (x0, y0, x1, y1)]}

js = ("/* GENERATED by scripts/build-mark-paths.py — do not edit.\n"
      "   Fraunces outlines for the monogram, instanced at opsz %d / wght %d,\n"
      "   in font units on a %d upem grid with y running UP.\n"
      "   Re-run: npm run mark */\n"
      "export const GLYPHS = %s;\n") % (OPSZ, WGHT, upem, json.dumps(out, indent=2, ensure_ascii=False))
(ROOT / "scripts/mark-paths.js").write_text(js, encoding="utf8")
print(f"    scripts/mark-paths.js — {len(js):,} bytes")
for ch, g in out["glyphs"].items():
    print(f"      {ch}  bbox {g['bbox']}  path {len(g['d']):,} chars")
