/**
 * Content-aware English → Chinese translation for the technical report.
 *
 *   node scripts/translate.mjs --status            what is translated, what is owed
 *   node scripts/translate.mjs --scan              re-segment the source into the memory
 *   node scripts/translate.mjs --assist [--limit N] [--section sec-x]
 *                                                 draft the units still owed
 *   node scripts/translate.mjs --review <id>...    mark units reviewed
 *   node scripts/translate.mjs --emit              write the Chinese .qmd
 *   node scripts/translate.mjs --check             validate the memory
 *
 * WHAT "CONTENT-AWARE" MEANS HERE
 * The report is 3,000 lines of prose with the machinery of a typeset document
 * running through it: inline LaTeX, `\index` entries, `@sec-` cross-references,
 * pipe tables, figure captions with attribute blocks, footnote references, CSS
 * variable names, hex values and file paths. Handing that to any translator as
 * plain text returns a document that no longer compiles and whose
 * cross-references point nowhere.
 *
 * So the source is segmented into units by KIND, and inside a unit every span
 * that is not prose is replaced by a sentinel before translation and restored
 * after. A translation that lost a sentinel is rejected rather than written.
 * The project's own vocabulary is applied on top of that, from the one corpus
 * in scripts/corpus.mjs — so the report says 作品 and 购买方式 because that is
 * what the site says, not because a translator happened to choose them.
 *
 * WHY THE BUILD NEVER TRANSLATES
 * Translation happens here, when a person runs it, and lands in a memory file
 * that is reviewed and committed. docs/report/build.sh only ever COMPOSES: it
 * reads the memory and writes the .qmd. Two reasons. A document that quotes
 * SAMR Order 37 verbatim must not have its statutory text regenerated by a
 * model on every build; and a PDF that needs the network to reproduce is not
 * reproducible. Each unit is keyed by a hash of its English, so editing an
 * English sentence marks its Chinese stale instead of leaving it silently
 * attached to text it no longer translates.
 *
 * WHAT AN UNTRANSLATED UNIT DOES
 * It falls back to English, and says so: `\zhmark{}` in the margin of the
 * passage, a count on the title page, and a line per unit in --status. The
 * same discipline as the site's NEEDS-INPUT marks — a gap a reader cannot see
 * is a gap nobody closes.
 */

import { readFileSync, writeFileSync, existsSync, mkdirSync } from 'node:fs';
import { join } from 'node:path';
import { createHash } from 'node:crypto';
import { spawnSync } from 'node:child_process';
import { loadCorpus, termsIn, relatedPhrases, phraseKey, termKey, ROOT } from './corpus.mjs';

const DOCDIR = join(ROOT, 'docs/report');
const SRC = join(DOCDIR, 'senso-comune-report.qmd');
const OUT = join(DOCDIR, 'senso-comune-report.zh.qmd');
const STRINGS = join(DOCDIR, 'report-zh-strings.tex');
const MEMDIR = join(DOCDIR, 'translations');
const MEM = join(MEMDIR, 'senso-comune-report.zh.json');
const STATUS = join(MEMDIR, 'STATUS.md');

const hash = (s) => createHash('sha256').update(s).digest('hex').slice(0, 12);
const today = () => new Date().toISOString().slice(0, 10);

/* ------------------------------------------------------------------ *
 * 1. THE SEGMENTER                                                    *
 *                                                                     *
 * A line-based pass over the .qmd. Every line ends up in exactly one   *
 * block, and every block either carries translatable units or is       *
 * carried through to the output verbatim. Nothing is dropped: --emit    *
 * reassembles the document from the block list, so a construct this    *
 * function does not understand survives as itself rather than being    *
 * quietly lost.                                                        *
 * ------------------------------------------------------------------ */

/** A callout's title is the one piece of prose inside a raw LaTeX block. */
const CALLOUT = /^\\begin\{(finding|blocker|openitem)\}\{(.+)\}\s*$/;
const HEADING = /^(#{1,6})\s+(.*?)\s*(\{#[^}]*\})?\s*$/;
const FIGURE = /^!\[(.*)\]\((\S+)\)(\{[^}]*\})?\s*$/;
const TBLCAP = /^:\s+(.+?)\s*(\{#tbl-[^}]*\})?\s*$/;
const FOOTNOTE = /^\[\^([A-Za-z0-9_-]+)\]:\s*(.*)$/;
const LISTITEM = /^(\s*)([-*+]|\d+\.)\s+(.*)$/;
const SEPROW = /^\|[\s:|-]+\|?\s*$/;

/** Slug for a heading with no explicit {#anchor}, so a unit id stays stable
 *  and readable rather than becoming an ordinal into the whole document. */
const slug = (s) => s.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-|-$/g, '').slice(0, 28) || 'x';

export function segment(text) {
  const lines = text.split('\n');
  const blocks = [];
  let i = 0;

  /* Front matter: the first --- fence pair. Only four of its keys are prose;
     the rest is configuration and is rewritten by --emit, not translated. */
  if (lines[0] === '---') {
    const end = lines.indexOf('---', 1);
    blocks.push({ kind: 'frontmatter', lines: lines.slice(0, end + 1) });
    i = end + 1;
  }

  let anchor = 'front';                       // nearest preceding section anchor
  const seen = new Map();                     // anchor -> per-kind counters
  const id = (kind) => {
    const c = seen.get(anchor) ?? (seen.set(anchor, {}), seen.get(anchor));
    c[kind] = (c[kind] ?? 0) + 1;
    return `${anchor}/${kind}${c[kind]}`;
  };

  while (i < lines.length) {
    const line = lines[i];

    if (line.trim() === '') { blocks.push({ kind: 'blank', lines: [line] }); i++; continue; }

    /* Fenced blocks pass through whole. A callout's title is lifted out of
       one; nothing else inside a fence is prose. */
    if (line.startsWith('```')) {
      const body = [line];
      i++;
      while (i < lines.length && !/^```\s*$/.test(lines[i])) body.push(lines[i++]);
      if (i < lines.length) body.push(lines[i++]);
      const b = { kind: 'raw', lines: body, units: [] };
      body.forEach((l, n) => {
        const m = l.match(CALLOUT);
        if (m) b.units.push({ id: id('callout'), kind: 'callout', en: m[2], at: n, env: m[1] });
      });
      blocks.push(b);
      continue;
    }

    const h = line.match(HEADING);
    if (h) {
      anchor = h[3] ? h[3].slice(2, -1).split(/\s+/)[0] : slug(h[2]);
      blocks.push({ kind: 'heading', hashes: h[1], attrs: h[3] ?? '',
                    units: [{ id: `${anchor}/head`, kind: 'heading', en: h[2] }] });
      i++; continue;
    }

    const f = line.match(FIGURE);
    if (f) {
      blocks.push({ kind: 'figure', src: f[2], attrs: f[3] ?? '',
                    units: [{ id: id('caption'), kind: 'caption', en: f[1] }] });
      i++; continue;
    }

    /* A table caption is a line beginning ": ". It is tested after the figure
       and heading so a colon opening an ordinary paragraph is not mistaken for
       one — Pandoc's own rule is that the caption line precedes the table. */
    const c = line.match(TBLCAP);
    if (c && lines[i + 1] !== undefined && !line.startsWith('::')) {
      blocks.push({ kind: 'tblcap', attrs: c[2] ?? '',
                    units: [{ id: id('tblcap'), kind: 'caption', en: c[1] }] });
      i++; continue;
    }

    if (line.startsWith('|')) {
      const rows = [];
      while (i < lines.length && lines[i].startsWith('|')) {
        const raw = lines[i];
        if (SEPROW.test(raw)) rows.push({ sep: true, raw });
        else {
          /* Split on unescaped pipes, keeping the leading and trailing empties
             so the row is rebuilt with exactly the pipes it had. */
          const parts = raw.split('|');
          const cells = parts.map((p, n) => {
            if (n === 0 || n === parts.length - 1) return { fixed: p };
            const t = p.trim();
            if (!t) return { fixed: p };
            return { pad: [p.match(/^\s*/)[0], p.match(/\s*$/)[0]],
                     unit: { id: id('cell'), kind: 'cell', en: t } };
          });
          rows.push({ cells });
        }
        i++;
      }
      const b = { kind: 'table', rows,
                  units: rows.flatMap((r) => r.cells?.map((c) => c.unit).filter(Boolean) ?? []) };
      blocks.push(b);
      continue;
    }

    const fn = line.match(FOOTNOTE);
    if (fn) {
      /* A footnote definition runs on while the next lines are indented. */
      const body = [fn[2]];
      i++;
      while (i < lines.length && /^\s{2,}\S/.test(lines[i])) body.push(lines[i++].trim());
      blocks.push({ kind: 'footnote', ref: fn[1],
                    units: [{ id: `${anchor}/fn-${fn[1]}`, kind: 'footnote', en: body.join(' ') }] });
      continue;
    }

    if (line.startsWith('> ') || line === '>') {
      const body = [];
      while (i < lines.length && (lines[i].startsWith('>') )) body.push(lines[i++].replace(/^>\s?/, ''));
      blocks.push({ kind: 'quote',
                    units: [{ id: id('quote'), kind: 'quote', en: body.join(' ').trim() }] });
      continue;
    }

    const li = line.match(LISTITEM);
    if (li) {
      const items = [];
      while (i < lines.length) {
        const m = lines[i].match(LISTITEM);
        if (!m) break;
        const body = [m[3]];
        i++;
        /* Continuation lines of one item are indented past its marker. A new
           marker at any indent starts a new item. */
        while (i < lines.length && lines[i].trim() !== '' && !LISTITEM.test(lines[i]) && /^\s+\S/.test(lines[i]))
          body.push(lines[i++].trim());
        items.push({ indent: m[1], marker: m[2],
                     unit: { id: id('item'), kind: 'item', en: body.join(' ') } });
      }
      blocks.push({ kind: 'list', items, units: items.map((x) => x.unit) });
      continue;
    }

    /* Anything else is a paragraph: to the next blank line or the next line
       that opens a block of its own. */
    const body = [];
    while (i < lines.length && lines[i].trim() !== '' && !lines[i].startsWith('```')
           && !lines[i].startsWith('|') && !HEADING.test(lines[i]) && !FIGURE.test(lines[i])
           && !FOOTNOTE.test(lines[i]) && !LISTITEM.test(lines[i]) && !lines[i].startsWith('>'))
      body.push(lines[i++]);
    blocks.push({ kind: 'para', units: [{ id: id('para'), kind: 'para', en: body.join('\n').trim() }] });
  }

  return blocks;
}

/* ------------------------------------------------------------------ *
 * 2. THE PROTECTOR                                                    *
 *                                                                     *
 * Every span inside a unit that must survive translation byte for byte *
 * is replaced by ⟦n⟧ before the text is shown to a translator, and     *
 * restored afterwards. The sentinel is checked: a translation missing  *
 * one, or carrying one twice, is rejected.                            *
 * ------------------------------------------------------------------ */

const SENTINEL = /⟦(\d+)⟧/g;

/** In priority order. The first pattern that matches at a position wins, so
 *  the more specific ones come first: an `\index{...}` is one span, not a
 *  backslash command beside a brace group, and `](url)` is protected before a
 *  bare URL so that a link's visible text stays translatable. */
const PATTERNS = [
  ['code',    /`[^`\n]+`/],                                     // file names, CSS variables, hex values
  ['dollar',  /\\\$[\d,.]+(?:\s*[–-]\s*\\\$[\d,.]+)?/],          // \$60–\$440
  ['tex',     /\\[a-zA-Z]+\*?(?:\[[^\]]*\])?(?:\{[^{}]*(?:\{[^{}]*\}[^{}]*)*\})*/],
  ['esc',     /\\[^a-zA-Z\s]/],                                  // \% \& \_ \~
  ['fnref',   /\[\^[A-Za-z0-9_-]+\]/],
  ['linkurl', /\]\((?:[^()\s]|\([^()]*\))+\)/],                  // the target of a link, not its text
  ['xref',    /@(?:sec|tbl|fig|eq|lst)-[A-Za-z0-9_-]+/],
  ['attrs',   /\{#[^}]*\}/],
  ['url',     /\bhttps?:\/\/[^\s)]+/],
  ['hex',     /#[0-9A-Fa-f]{6}\b/],
  ['ratio',   /\b\d+(?:\.\d+)?\s*:\s*\d+(?:\.\d+)?\b/],          // 4.92:1
  ['measure', /\b\d[\d,.]*\s?(?:px|pt|mm|cm|dpi|KB|MB|GB|kB|%|dpi)\b/],
  ['dim',     /\b\d[\d.]*\s?[x×]\s?\d[\d.]*\s?(?:px|pt|mm|cm)?\b/],
];

/** Terms that must appear in Latin script in the Chinese, longest first so
 *  "Cloudflare Pages" is protected as one span rather than as "Cloudflare"
 *  followed by a translatable word. */
function keepPattern(keep) {
  const alts = [...keep].sort((a, b) => b.length - a.length)
    .map((k) => k.replace(/[.*+?^${}()|[\]\\]/g, '\\$&'));
  return new RegExp(`(?<![A-Za-z0-9])(?:${alts.join('|')})(?![A-Za-z0-9])`);
}

export function protect(text, keepRe) {
  const spans = [];
  const pats = keepRe ? [...PATTERNS, ['keep', keepRe]] : PATTERNS;
  let out = '', pos = 0;
  outer: while (pos < text.length) {
    for (const [kind, re] of pats) {
      const r = new RegExp(re.source, re.flags.includes('g') ? re.flags : re.flags + 'g');
      r.lastIndex = pos;
      const m = r.exec(text);
      if (m && m.index === pos) {
        spans.push({ kind, text: m[0] });
        out += `⟦${spans.length}⟧`;
        pos += m[0].length;
        continue outer;
      }
    }
    out += text[pos++];
  }
  return { masked: out, spans };
}

export function restore(masked, spans) {
  const missing = [];
  const used = new Set();
  const text = masked.replace(SENTINEL, (_, n) => {
    const s = spans[Number(n) - 1];
    if (!s) { missing.push(`⟦${n}⟧ has no span`); return ''; }
    if (used.has(n)) missing.push(`⟦${n}⟧ appears more than once`);
    used.add(n);
    return s.text;
  });
  for (let n = 1; n <= spans.length; n++) if (!used.has(String(n)))
    missing.push(`⟦${n}⟧ (${spans[n - 1].kind} ${JSON.stringify(spans[n - 1].text.slice(0, 28))}) was dropped`);
  return { text, missing };
}

/* ------------------------------------------------------------------ *
 * 3. THE MEMORY                                                       *
 * ------------------------------------------------------------------ */

const emptyMem = () => ({
  $comment: [
    'Translation memory for the technical report. Written by',
    'scripts/translate.mjs; reviewed and committed by hand.',
    '',
    'One entry per translatable unit, in document order. `hash` is over the',
    'English: edit the English and the entry goes stale, which is reported by',
    '--status and by scripts/check-corpus.mjs rather than left to be noticed.',
    '',
    'status: draft    proposed, not yet read by a person',
    '        reviewed read and accepted — the only status that is finished',
  ],
  source: 'senso-comune-report.qmd',
  units: {},
});

const loadMem = () => (existsSync(MEM) ? JSON.parse(readFileSync(MEM, 'utf8')) : emptyMem());

function saveMem(mem, order) {
  mkdirSync(MEMDIR, { recursive: true });
  /* Serialised in document order with one unit per line, so a diff shows the
     passage that changed rather than a reordered file. */
  const head = JSON.stringify({ $comment: mem.$comment, source: mem.source }, null, 1).replace(/\n\}$/, '');
  const body = order.filter((id) => mem.units[id]).map((id) => {
    const u = mem.units[id];
    return ` ${JSON.stringify(id)}: ${JSON.stringify(u)}`;
  }).join(',\n');
  const text = `${head},\n "units": {\n${body}\n }\n}\n`;
  /* Written only when it changed. Every command here begins with a scan, so a
     --status or a --check would otherwise touch the file on every run — which
     makes the memory look newer than the document composed from it, and
     scripts/check-corpus.mjs (L-04) rightly calls that stale. Idempotent, for
     the same reason fonts.py is. */
  if (existsSync(MEM) && readFileSync(MEM, 'utf8') === text) return false;
  writeFileSync(MEM, text);
  return true;
}

/* ------------------------------------------------------------------ *
 * 4. SCAN — segment the source and carry the memory over              *
 * ------------------------------------------------------------------ */

function allUnits(blocks) {
  return blocks.flatMap((b) => b.units ?? []);
}

function scan({ quiet = false } = {}) {
  const corpus = loadCorpus();
  const keepRe = keepPattern(corpus.keep);
  const blocks = segment(readFileSync(SRC, 'utf8'));
  const units = allUnits(blocks);
  const mem = loadMem();
  const prev = mem.units;
  const byHash = new Map();
  for (const [id, u] of Object.entries(prev)) if (u.zh) byHash.set(u.hash, { id, ...u });

  const next = {};
  const report = { kept: 0, moved: [], stale: [], fresh: [], retired: [], seeded: [] };

  for (const u of units) {
    const h = hash(u.en);
    const old = prev[u.id];
    if (old?.hash === h && old.zh) { next[u.id] = { ...old, kind: u.kind }; report.kept++; continue; }

    /* The unit's text is unchanged but its id moved — prose was inserted above
       it. Carry the Chinese across by hash: this is the whole reason a memory
       is keyed by content as well as by position. */
    const moved = byHash.get(h);
    if (moved && moved.id !== u.id) {
      next[u.id] = { kind: u.kind, en: u.en, hash: h, zh: moved.zh, status: moved.status, at: moved.at, wasAt: moved.id };
      report.moved.push(`${moved.id} → ${u.id}`);
      continue;
    }

    /* A sentence the site already says, in the site's own Chinese. The
       strongest form of one corpus: the report does not re-translate the
       returns policy, it quotes it. */
    const seed = corpus.phrases.get(phraseKey(u.en));
    if (seed) {
      next[u.id] = { kind: u.kind, en: u.en, hash: h, zh: seed.zh, status: 'draft', at: today(), from: seed.from };
      report.seeded.push(u.id);
      continue;
    }

    if (old?.zh) {
      next[u.id] = { kind: u.kind, en: u.en, hash: h, zh: old.zh, status: 'stale', at: old.at, wasHash: old.hash };
      report.stale.push(u.id);
      continue;
    }
    next[u.id] = { kind: u.kind, en: u.en, hash: h, zh: '', status: 'owed' };
    report.fresh.push(u.id);
  }

  for (const id of Object.keys(prev)) if (!next[id]) report.retired.push(id);

  mem.units = next;
  saveMem(mem, units.map((u) => u.id));

  if (!quiet) {
    console.log(`\n  ${units.length} units in ${blocks.length} blocks`);
    console.log(`    ${report.kept} unchanged`);
    if (report.moved.length)  console.log(`    ${report.moved.length} carried across a move`);
    if (report.seeded.length) console.log(`    ${report.seeded.length} seeded from the site's own Chinese`);
    if (report.stale.length)  console.log(`    ${report.stale.length} STALE — the English changed under a translation`);
    if (report.fresh.length)  console.log(`    ${report.fresh.length} new, owed`);
    if (report.retired.length) console.log(`    ${report.retired.length} retired (text no longer in the document)`);
    console.log('');
  }
  return { blocks, units, mem, corpus, keepRe, report };
}

/* ------------------------------------------------------------------ *
 * 5. ASSIST — draft the units that are owed                           *
 *                                                                     *
 * Runs the local `claude` CLI. This is an authoring step, never a build *
 * step: it writes drafts into the memory for a person to read.          *
 * ------------------------------------------------------------------ */

const RULES = `You are translating a technical report from English into Simplified Chinese.
The report is about a small gallery website that sells paintings from mainland China.

Rules, in order of importance:

1. ⟦1⟧, ⟦2⟧ … are sentinels standing for code, file names, CSS variables, hex
   colours, cross-references, measurements, URLs and names that must not be
   translated. Reproduce every sentinel exactly, once each, in the position the
   Chinese sentence needs it. Never invent, drop, renumber or duplicate one.
2. Use the glossary below for every term it covers. It is the vocabulary the
   website itself already uses; consistency with it matters more than elegance.
3. Keep Markdown emphasis exactly: **bold** stays **bold**, *italic* stays
   *italic*, with the same number of markers.
4. Use full-width Chinese punctuation (，。；：？！——（）) in Chinese sentences.
   Do not put a space between a Chinese character and a sentinel.
5. Translate meaning, not words. Keep the register: this is a report to one
   non-technical owner, direct and unpadded. Do not add, remove, soften or
   summarise anything, and do not add explanations the English does not have.
6. Return one <zh> block per <unit>, with the same id, and nothing else.`;

function assistPrompt(batch, corpus) {
  const terms = new Map();
  for (const u of batch) {
    for (const e of termsIn(u.masked, corpus, { enforced: true })) terms.set(e.en, e.zh);
    /* And the terms named in this unit's index entries. An \index{} argument is
       masked out of the prose — it has to be, it is a command — but it is also
       the project's settled name for what the passage is about, and --emit
       translates it from the corpus. Without this, "Rome I\index{Rome I
       Regulation}" came out as 罗马第一条例 in the paragraph and 罗马条例 I in
       the index: one concept, two names, in one document.
       Offered, not enforced. The prose is often right to use the abbreviation
       the English uses — "CRD\index{Consumer Rights Directive}" — and demanding
       the full Chinese name there would be wrong. */
    for (const m of u.en.matchAll(/\\index\{([^}]*)\}/g)) {
      const e = corpus.terms.get(termKey(m[1]));
      if (e && !corpus.keep.has(e.en)) terms.set(e.en, e.zh);
    }
  }
  const glossary = [...terms].map(([en, zh]) => `  ${en} → ${zh}`).join('\n') || '  (none in this batch)';

  /* How the site already says related things. The terms fix the words; these
     fix the register — the site's Chinese is the only Chinese this project has
     published, and a report that reads like it was written by the same person
     is the point of having one corpus. */
  const seen = new Set();
  const related = [];
  for (const u of batch)
    for (const e of relatedPhrases(u.masked, corpus, { limit: 2 }))
      if (!seen.has(e.en)) { seen.add(e.en); related.push(e); }
  const register = related.slice(0, 4)
    .map((e) => `  EN: ${e.en}\n  ZH: ${e.zh}`).join('\n\n');

  const units = batch.map((u) => `<unit id="${u.id}" kind="${u.kind}">\n${u.masked}\n</unit>`).join('\n\n');
  return `${RULES}\n\nGlossary for this batch:\n${glossary}\n`
    + (register ? `\nHow the website itself says related things. Match this register and these\nword choices; do not copy the sentences, they are not translations of the\nunits below:\n\n${register}\n` : '')
    + `\nUnits:\n\n${units}\n\nReturn only <zh id="...">…</zh> blocks.`;
}

function callClaude(prompt) {
  const r = spawnSync('claude', ['-p', prompt], { encoding: 'utf8', maxBuffer: 1 << 26 });
  if (r.error) throw new Error(`could not run the claude CLI: ${r.error.message}`);
  if (r.status !== 0) throw new Error(`claude exited ${r.status}: ${(r.stderr || '').slice(0, 400)}`);
  return r.stdout;
}

function parseAssist(out) {
  const got = new Map();
  for (const m of out.matchAll(/<zh id="([^"]+)"[^>]*>\n?([\s\S]*?)<\/zh>/g)) got.set(m[1], m[2].trim());
  return got;
}

async function assist(opts) {
  const { units, mem, corpus, keepRe } = scan({ quiet: true });
  const owed = units.filter((u) => {
    const m = mem.units[u.id];
    if (!m) return false;
    if (m.status === 'reviewed') return false;          // a person accepted it; leave it alone
    if (opts.section && !u.id.startsWith(`${opts.section}/`)) return false;
    if (!m.zh || m.status === 'stale') return true;     // owed, or the English moved under it
    return opts.redraft;                                // an existing draft, only if asked for
  }).slice(0, opts.limit ?? Infinity);

  if (!owed.length) { console.log('\n  nothing owed a draft\n'); return; }

  /* Batched by character budget rather than by count: one table of short cells
     and one page of prose are very different amounts of text. */
  const BUDGET = 3500;
  const batches = [];
  let cur = [], size = 0;
  for (const u of owed) {
    const { masked, spans } = protect(u.en, keepRe);
    const item = { ...u, masked, spans };
    if (size + masked.length > BUDGET && cur.length) { batches.push(cur); cur = []; size = 0; }
    cur.push(item); size += masked.length;
  }
  if (cur.length) batches.push(cur);

  console.log(`\n  ${owed.length} units owed, in ${batches.length} batch(es)\n`);
  let ok = 0, rejected = 0;
  for (const [n, batch] of batches.entries()) {
    process.stdout.write(`  batch ${n + 1}/${batches.length} (${batch.length} units) … `);
    let got;
    try { got = parseAssist(callClaude(assistPrompt(batch, corpus))); }
    catch (e) { console.log(`failed: ${e.message}`); continue; }
    let good = 0;
    for (const u of batch) {
      const masked = got.get(u.id);
      if (masked === undefined) { rejected++; continue; }
      const { text, missing } = restore(masked, u.spans);
      if (missing.length) {
        console.log(`\n      ✗ ${u.id}: ${missing[0]}`);
        rejected++; continue;
      }
      mem.units[u.id] = { kind: u.kind, en: u.en, hash: hash(u.en), zh: text, status: 'draft', at: today() };
      good++; ok++;
    }
    console.log(`${good} drafted`);
    saveMem(mem, units.map((x) => x.id));
  }
  console.log(`\n  ${ok} drafted, ${rejected} rejected. Read them: node scripts/translate.mjs --status\n`);
}

/* ------------------------------------------------------------------ *
 * 6. VALIDATE                                                         *
 * ------------------------------------------------------------------ */

const CJK = /[㐀-䶿一-鿿]/;
/** ASCII punctuation that should be full-width when it separates Chinese. */
const HALFWIDTH = /[一-鿿][,;:!?]|[,;:!?][一-鿿]/;

export function validate() {
  const { units, mem, corpus, keepRe } = scan({ quiet: true });
  const findings = [];
  const add = (id, what, detail) => findings.push({ id, what, detail });

  for (const u of units) {
    const m = mem.units[u.id];
    if (!m) { add(u.id, 'missing from the memory', 'run --scan'); continue; }
    if (!m.zh) continue;                                  // owed, and counted as owed
    if (m.status === 'stale') { add(u.id, 'stale', 'the English changed under this translation'); continue; }

    const { masked, spans } = protect(u.en, keepRe);
    /* Every protected span must survive verbatim in the Chinese. */
    for (const s of spans) if (!m.zh.includes(s.text))
      add(u.id, `dropped a ${s.kind}`, JSON.stringify(s.text.slice(0, 40)));

    const marks = (s, re) => (s.match(re) ?? []).length;
    if (marks(u.en, /\*\*/g) !== marks(m.zh, /\*\*/g)) add(u.id, 'bold markers do not match', `en ${marks(u.en, /\*\*/g)}, zh ${marks(m.zh, /\*\*/g)}`);

    if (!CJK.test(m.zh) && CJK.test(u.en) === false && u.en.length > 24)
      add(u.id, 'no Chinese in the translation', JSON.stringify(m.zh.slice(0, 40)));
    if (HALFWIDTH.test(m.zh)) add(u.id, 'half-width punctuation between Chinese', JSON.stringify(m.zh.match(HALFWIDTH)[0]));

    /* The corpus is the point of the exercise: a term the project has settled
       must appear as the project's Chinese for it.
       Read against the MASKED text, not the English: `check-contrast` is a file
       name and @sec-sage-ground is a cross-reference, and finding the terms
       "check" and "ground" inside them reported two passages that were in fact
       correct. A term has to be in the prose to be a term in the prose. */
    for (const e of termsIn(masked, corpus, { enforced: true })) {
      if (corpus.keep.has(e.en)) continue;
      const wanted = [e.zh, ...(e.alt ?? [])];
      if (!wanted.some((w) => m.zh.includes(w)))
        add(u.id, 'off-corpus term', `"${e.en}" should read ${wanted.map((w) => `"${w}"`).join(' or ')} (${e.from})`);
    }
  }

  const owed = units.filter((u) => !mem.units[u.id]?.zh);
  const draft = units.filter((u) => mem.units[u.id]?.status === 'draft');
  const reviewed = units.filter((u) => mem.units[u.id]?.status === 'reviewed');
  return { findings, units, owed, draft, reviewed, mem, corpus };
}

/* ------------------------------------------------------------------ *
 * 7. EMIT — compose the Chinese .qmd                                  *
 * ------------------------------------------------------------------ */

/** `\index{Hong Kong entity}` → `\index{香港实体}`, from the corpus only. An
 *  index entry is never drafted: it is either a term the project has settled
 *  or it stays in English, because an index sorted on a guess is worse than
 *  one a reader can still use. */
function indexZh(tex, corpus) {
  return tex.replace(/\\index\{([^}]*)\}/g, (all, arg) => {
    const e = corpus.terms.get(arg.toLowerCase().replace(/\s+/g, ' '));
    return e && !corpus.keep.has(e.en) ? `\\index{${e.zh}}` : all;
  });
}

/** "21 September 2026" -> "2026 年 9 月 21 日". The one piece of prose in the front
 *  matter with a fixed form, so it is converted rather than translated: a
 *  drafted date is a date that can be wrong. */
const MONTHS = ['January', 'February', 'March', 'April', 'May', 'June', 'July',
                'August', 'September', 'October', 'November', 'December'];
/** The `date:` the English front matter carries. */
function srcDate(blocks) {
  const fm = blocks.find((b) => b.kind === 'frontmatter');
  return fm?.lines.join('\n').match(/^date:\s*"?([^"\n]+)"?\s*$/m)?.[1]?.trim() ?? '';
}

function dateZh(d) {
  const m = d.match(/^(\d{1,2})\s+([A-Za-z]+)\s+(\d{4})$/);
  if (!m) return d;
  const mo = MONTHS.findIndex((x) => x.toLowerCase() === m[2].toLowerCase()) + 1;
  return mo ? `${m[3]} 年 ${mo} 月 ${Number(m[1])} 日` : d;
}

/** A page capture has a Chinese counterpart: shots.sh shoots every route on
 *  both sides of the site. Swap to it when the file is there, and leave the
 *  English capture alone when it is not — an edition must not fail to build
 *  over a screenshot, and the figures that are not page captures (the palette,
 *  the contrast plates, the mark) have no language at all. */
function figZh(src) {
  const zh = src.replace(/(^|\/)cap-(?!zh-)/, '$1cap-zh-');
  return zh !== src && existsSync(join(DOCDIR, zh)) ? zh : src;
}

const GAP = '\\zhmark{}';

function emit() {
  const { blocks, mem, corpus } = scan({ quiet: true });
  let gaps = 0;
  const zhOf = (u, { inline = false } = {}) => {
    const m = mem.units[u.id];
    if (m?.zh && m.status !== 'stale') return { text: m.zh, gap: false };
    gaps++;
    /* Fall back to the English, marked. Inline positions — a heading, a table
       cell, a caption — take the mark too: it is one small superscript and it
       is the only thing that makes the gap visible in the PDF. */
    return { text: inline ? `${u.en}${GAP}` : `${GAP}${u.en}`, gap: true };
  };

  const out = [];
  for (const b of blocks) {
    switch (b.kind) {
      case 'frontmatter': {
        /* Rewritten rather than translated line by line: four of its keys are
           prose, two are typesetting decisions that differ for Chinese, and
           one more header file is added. */
        const src = b.lines.join('\n');
        const F = corpus.furniture;
        /* The title is the gallery's own Chinese name, taken from the corpus
           (seller.json -> artist.siteName) rather than written again here. */
        const title = corpus.terms.get('senso comune gallery')?.zh ?? '常识画廊';
        const fm = src
          .replace(/^title:.*$/m, `title: "${title}"`)
          .replace(/^subtitle:.*$/m, `subtitle: "${F.subtitle.zh}"`)
          .replace(/^author:.*$/m, `author: "${F.preparedFor.zh} Priscilla"`)
          /* `lang` is deliberately NOT switched to zh. Quarto answers a
             language by loading babel or polyglossia for it, neither of which
             sets Chinese without a locale package, and both of which then
             argue with xeCJK under tectonic. Every visible effect `lang` would
             have — \contentsname, \figurename, \tablename, \indexname and the
             PDF's own language — is set explicitly in preamble-zh.tex instead,
             where it is this project's decision rather than a side effect. */
          .replace(/^lang:\s*en\s*$/m, 'lang: en   # see preamble-zh.tex: the Chinese names are set there, not by Quarto')
          /* Chinese needs more leading than Latin at the same size: a page of
             han characters is denser and the lines lock up without it. The key
             is nested under `format: pdf:`, so its indent is kept. */
          .replace(/^(\s*)linestretch:.*$/m, '$1linestretch: 1.45')
          /* The contents heading is the one name a preamble cannot reach:
             pandoc writes `\renewcommand*\contentsname{Table of contents}` into
             the document BODY, on the line before \tableofcontents, so no hook
             anywhere in the preamble survives it. `toc-title` is the metadata
             that string comes from. The other five names are set in
             preamble-zh.tex, which is where they can be. */
          .replace(/^toc:\s*true\s*$/m, `toc: true\ntoc-title: "${F.contents.zh}"`)
          .replace(/^(include-in-header:\n(?:\s+- .*\n)*)/m, '$1  - report-zh-strings.tex\n  - preamble-zh.tex\n');
        out.push(fm);
        break;
      }
      case 'raw': {
        const lines = [...b.lines];
        for (const u of b.units) {
          const { text } = zhOf(u, { inline: true });
          lines[u.at] = `\\begin{${u.env}}{${text}}`;
        }
        out.push(indexZh(lines.join('\n'), corpus)
          .replace(/\\renewcommand\{\\indexname\}\{Index\}/, `\\renewcommand{\\indexname}{${corpus.furniture.index.zh}}`)
          .replace(/\\addcontentsline\{toc\}\{part\}\{Index\}/, `\\addcontentsline{toc}{part}{${corpus.furniture.index.zh}}`));
        break;
      }
      case 'heading': {
        const { text } = zhOf(b.units[0], { inline: true });
        out.push(`${b.hashes} ${indexZh(text, corpus)}${b.attrs ? ` ${b.attrs}` : ''}`);
        break;
      }
      case 'figure': {
        const { text } = zhOf(b.units[0], { inline: true });
        out.push(`![${indexZh(text, corpus)}](${figZh(b.src)})${b.attrs}`);
        break;
      }
      case 'tblcap': {
        const { text } = zhOf(b.units[0], { inline: true });
        out.push(`: ${indexZh(text, corpus)}${b.attrs ? ` ${b.attrs}` : ''}`);
        break;
      }
      case 'table': {
        for (const r of b.rows) {
          if (r.sep) { out.push(r.raw); continue; }
          out.push(r.cells.map((c) => {
            if (c.fixed !== undefined) return c.fixed;
            const { text } = zhOf(c.unit, { inline: true });
            return c.pad[0] + indexZh(text, corpus) + c.pad[1];
          }).join('|'));
        }
        break;
      }
      case 'footnote': {
        const { text } = zhOf(b.units[0]);
        out.push(`[^${b.ref}]: ${indexZh(text, corpus)}`);
        break;
      }
      case 'quote': {
        const { text } = zhOf(b.units[0]);
        out.push(`> ${indexZh(text, corpus)}`);
        break;
      }
      case 'list': {
        for (const it of b.items) {
          const { text } = zhOf(it.unit);
          out.push(`${it.indent}${it.marker} ${indexZh(text, corpus)}`);
        }
        break;
      }
      case 'para': {
        const { text, gap } = zhOf(b.units[0]);
        /* On ONE line when it is Chinese. Pandoc joins the lines of a
           paragraph with a space, and a space between two han characters is
           visible — a wrapped Chinese paragraph comes out gapped at every line
           the author happened to break. English falls back wrapped as it was. */
        out.push(gap ? text : indexZh(text, corpus).replace(/\n+/g, ''));
        break;
      }
      default: out.push(b.lines.join('\n'));
    }
  }

  /* No trailing newline is added: splitting the source on '\n' already left a
     final empty line as its own blank block, so joining reproduces the file's
     ending exactly rather than growing one blank line per build. */
  writeFileSync(OUT, out.join('\n'));

  /* The furniture, as LaTeX. Generated, so the words live in the lexicon with
     everything else rather than in a second copy inside a .tex file. */
  const F = corpus.furniture;
  const total = Object.values(mem.units).length;
  const strings = [
    '% Generated by scripts/translate.mjs — do not edit.',
    '% The document\'s furniture, in Chinese. Every one of these is a macro that',
    '% preamble.tex defines with the English as its default; this file only ever',
    '% renews them, so the layout is not duplicated for the second language.',
    '',
    ...Object.entries(F).map(([k, v]) =>
      `\\renewcommand{\\sc${k}}{${v.zh}}`),
    '',
    `% The date as Chinese reads one. The front matter keeps the English form,`,
    `% because Quarto parses that field and returns "Invalid Date" for a date it`,
    `% cannot read — so the value is rendered here instead of there.`,
    `\\renewcommand{\\scdateValue}{${dateZh(srcDate(blocks))}}`,
    ``,
    `% What is still English, so the title page can say so rather than let a`,
    `% reader discover it halfway down page 40.`,
    `\\renewcommand{\\sczhgaps}{${gaps}}`,
    `\\renewcommand{\\sczhtotal}{${total}}`,
  ].join('\n') + '\n';
  writeFileSync(STRINGS, strings);

  writeStatus(validate());

  console.log(`  ${OUT.replace(ROOT + '/', '')}  —  ${out.length} blocks, ${total} units, ${gaps} still English`);
  return { gaps, total };
}

/* ------------------------------------------------------------------ *
 * 8. STATUS                                                          *
 * ------------------------------------------------------------------ */

/** docs/report/translations/STATUS.md — the same numbers --status prints, as a
 *  file a reader can open without running anything. Written by --emit as well,
 *  so the record and the composed document are never a build apart. */
function writeStatus(v) {
  const byKind = {};
  for (const u of v.units) {
    const s = v.mem.units[u.id];
    const k = byKind[u.kind] ?? (byKind[u.kind] = { total: 0, reviewed: 0, draft: 0, owed: 0, stale: 0 });
    k.total++;
    if (!s?.zh) k.owed++;
    else if (s.status === 'stale') k.stale++;
    else k[s.status === 'reviewed' ? 'reviewed' : 'draft']++;
  }
  const pct = (n, d) => (d ? `${Math.round((n / d) * 100)}%` : '—');
  const rows = Object.entries(byKind).sort((a, b) => b[1].total - a[1].total);

  const lines = [];
  lines.push('# Chinese report — translation status', '',
    `Generated by \`node scripts/translate.mjs --status\` on ${today()}.`, '',
    '| Unit kind | Total | Reviewed | Draft | Stale | Owed |',
    '|:----------|------:|---------:|------:|------:|-----:|');
  for (const [kind, k] of rows)
    lines.push(`| ${kind} | ${k.total} | ${k.reviewed} | ${k.draft} | ${k.stale} | ${k.owed} |`);
  const T = v.units.length;
  lines.push(`| **all** | **${T}** | **${v.reviewed.length}** (${pct(v.reviewed.length, T)}) | **${v.draft.length}** | **${v.units.filter((u) => v.mem.units[u.id]?.status === 'stale').length}** | **${v.owed.length}** |`, '');

  if (v.findings.length) {
    lines.push(`## ${v.findings.length} finding(s)`, '');
    for (const f of v.findings.slice(0, 200)) lines.push(`- \`${f.id}\` — ${f.what}: ${f.detail}`);
    if (v.findings.length > 200) lines.push(`- … and ${v.findings.length - 200} more`);
    lines.push('');
  } else lines.push('No findings: every translation in the memory carries its code, its', 'cross-references and the project\'s own vocabulary.', '');

  mkdirSync(MEMDIR, { recursive: true });
  const text = lines.join('\n');
  if (!existsSync(STATUS) || readFileSync(STATUS, 'utf8') !== text) writeFileSync(STATUS, text);
  return { rows, T, pct };
}

function status() {
  const v = validate();
  const { rows, T, pct } = writeStatus(v);

  console.log(`\n  ${T} units — ${v.reviewed.length} reviewed (${pct(v.reviewed.length, T)}), ${v.draft.length} draft, ${v.owed.length} owed`);
  for (const [kind, k] of rows)
    console.log(`    ${kind.padEnd(9)} ${String(k.total).padStart(5)}  reviewed ${String(k.reviewed).padStart(4)}  draft ${String(k.draft).padStart(4)}  owed ${String(k.owed).padStart(4)}`);
  if (v.findings.length) {
    console.log(`\n  ${v.findings.length} finding(s); first ten:`);
    for (const f of v.findings.slice(0, 10)) console.log(`    ✗ ${f.id} — ${f.what}: ${f.detail}`);
  }
  console.log(`\n  written: ${STATUS.replace(ROOT + '/', '')}\n`);
  return v;
}

/* ------------------------------------------------------------------ */

const argv = process.argv.slice(2);
const flag = (n) => argv.includes(`--${n}`);
const val = (n) => { const i = argv.indexOf(`--${n}`); return i < 0 ? undefined : argv[i + 1]; };

if (import.meta.url === `file://${process.argv[1]}`) {
  if (flag('scan')) scan();
  else if (flag('assist')) await assist({ limit: Number(val('limit')) || undefined, section: val('section'), redraft: flag('redraft') });
  else if (flag('emit')) { scan({ quiet: true }); emit(); }
  else if (flag('review')) {
    const mem = loadMem();
    const ids = argv.filter((a) => !a.startsWith('--'));
    const { units } = scan({ quiet: true });
    let n = 0;
    for (const id of ids) if (mem.units[id]?.zh) { mem.units[id].status = 'reviewed'; n++; }
    saveMem(mem, units.map((u) => u.id));
    console.log(`\n  ${n} unit(s) marked reviewed\n`);
  } else if (flag('check')) {
    const v = validate();
    if (v.findings.length) {
      console.error(`\n  translation memory: ${v.findings.length} finding(s)`);
      for (const f of v.findings.slice(0, 20)) console.error(`    ✗ ${f.id} — ${f.what}: ${f.detail}`);
      process.exit(1);
    }
    console.log(`  translation memory: ${v.units.length} units, ${v.owed.length} owed, no findings`);
  } else status();
}

export { scan, emit, status, MEM, OUT, STRINGS };
